#!/bin/sh /etc/rc.common
START=85
USE_PROCD=1

append_arg() {
    local cfg="$1"
    local var="$2"
    local opt="$3"
    local def="$4"
    local val
    config_get val "$cfg" "$var"
    [ -n "$val" -o -n "$def" ] && procd_append_param command "$opt" "${val:-$def}"
}

add_instance() {
	local cfg=$1
	local enabled
	config_get_bool enabled "$cfg" enabled 0
	[ $enabled -gt 0 ] || { echo "Output service not enabled"; exit 1; }
	procd_open_instance
	procd_set_param command output-sparkfun
	append_arg "$cfg" public "-p"
	append_arg "$cfg" key "-k"
	# no, we let monit take care of it.  for now...
	#procd_set_param respawn
	procd_close_instance
}

start_service() {
    config_load output-sparkfun && config_foreach add_instance general
}

