#!/bin/sh /etc/rc.common
START=85
USE_PROCD=1

remove_output() {
	local cfg="$1"
	local connection
	config_get connection "$cfg" connection
	[ -n "$connection" -a "$connection" = "activitystream" ] && {
		uci delete mosquitto.$cfg
	}
}

add_output() {
	local routing_key="$1"
	local username="$2"
	local password="$3"
	local address="$4"
	local connection
	local newcfg
	newcfg=$(uci add mosquitto bridge)
	uci -q batch <<-EOF
		set mosquitto.$newcfg.connection=activitystream
		set mosquitto.$newcfg.address="$address"
		set mosquitto.$newcfg.cleansession=0
		set mosquitto.$newcfg.keepalive=30
		set mosquitto.$newcfg.attempt_unsubscribe=false
		set mosquitto.$newcfg.notifications=false
		set mosquitto.$newcfg.try_private=false
		set mosquitto.$newcfg.capath=/etc/ssl/certs
		set mosquitto.$newcfg.remote_username="$username"
		set mosquitto.$newcfg.remote_password="$password"
		add_list mosquitto.$newcfg.topic="/json/device/# out 1 status/local status/$routing_key"
		add_list mosquitto.$newcfg.topic="/json/cabinet/# out 1 status/local status/$routing_key"
		commit
EOF
}

add_instance() {
	local cfg="$1"
	local enabled routing_key username password
	config_get_bool enabled "$cfg" enabled 0
	config_get routing_key "$cfg" routing_key
	config_get username "$cfg" username
	config_get password "$cfg" password
	config_get address "$cfg" address "mq.activitystream.com:8883"
	# We always remove it, and re-add it if needed.
	config_load mosquitto && config_foreach remove_output bridge
	if [ $enabled -eq 0 ]; then
		echo "Disabling Activity Stream"
	else
		[ -z "$routing_key" ] && { echo "routing_key is required!"; exit 1;}
		[ -z "$username" ] && { echo "username is required!"; exit 1;}
		[ -z "$password" ] && { echo "password is required!"; exit 1;}
		echo "Enabling Activity Stream"
		add_output $routing_key $username $password $address
	fi
	uci commit
	reload_config
}

start_service() {
	procd_open_instance
	# Just something that succeeds
	procd_set_param command true
	procd_set_param file /etc/config/output-activitystream
	procd_close_instance
	config_load output-activitystream && config_foreach add_instance general
}

service_triggers() {
	procd_add_reload_trigger output-activitystream
}
