#!/bin/sh
# Karl Palsson, <karlp@etactica.com> Sept 2018

CFG=output-statsd
[ -f /etc/config/$CFG ] && exit 0

# Create an example file if it doesn't exist already.
touch /etc/config/$CFG
uci -q batch <<-EOF >/dev/null
		set mlifter.remake.include_simple_json='1'
		commit mlifter
		delete $CFG.@general[0]
		add $CFG general
		set $CFG.@general[0]=general
		set $CFG.@general[0].enabled=0
		set $CFG.@general[0].statsd_host=localhost
		set $CFG.@general[0].statsd_port=8125
		commit $CFG
EOF

# Helps us work if we're installed later
rm -f /tmp/luci-indexcache

exit 0
