#!/bin/sh
# Karl Palsson, <karlp@etactica.com> Sept 2018

CFG=output-db
[ -f /etc/config/$CFG ] && exit 0

# Create an example file if it doesn't exist already.
touch /etc/config/$CFG
uci -q batch <<-EOF >/dev/null 
		set $CFG.mydatasink=instance
		set $CFG.mydatasink.enabled=0
		set $CFG.mydatasink.driver=postgres
		commit $CFG
EOF

# Helps us work if we're installed later
rm -f /tmp/luci-indexcache

exit 0
