#!/bin/sh
# Karl Palsson, <karlp@etactica.com> Oct 2017

CFG=output-activitystream
[ -f /etc/config/$CFG ] && exit 0

# Create an example file if it doesn't exist already.
touch /etc/config/$CFG
uci -q batch <<-EOF >/dev/null 
		delete $CFG.@general[0]
		add $CFG general
		set $CFG.@general[0]=general
		set $CFG.@general[0].enabled=0
		set $CFG.@general[0].routing_key=example-key
		set $CFG.@general[0].username=example-username
		set $CFG.@general[0].password=example-password
		set $CFG.@general[0].address=mq.activitystream.com:8883
		commit $CFG
EOF

# Add a ucitrack entry, until such time as luci uses reload_config :|
uci -q batch <<-EOF >/dev/null
        delete ucitrack.@$CFG[-1]
        add ucitrack $CFG
        set ucitrack.@$CFG[-1].init=$CFG
        commit ucitrack
EOF

# Helps us work if we're installed later
rm -f /tmp/luci-indexcache

exit 0