#!/bin/sh /etc/rc.common
START=85
USE_PROCD=1
APP=output-db

add_instance() {
	local cfg="$1"
	local enabled
	config_get_bool enabled "$cfg" enabled 0
	if [ $enabled -eq 0 ]; then
	  # FIXME - need to monitor all instances!
		# monit unmonitor "$APP"
		printf "%s:%s is disabled, not starting\n" "$APP" "$cfg"
	else
		procd_open_instance
		procd_set_param command output-db.lua
		procd_set_param file /etc/config/$APP
		# This is only for monit monitoring
		procd_set_param pidfile /var/run/$APP.$cfg.pid
		procd_append_param command -i $cfg
		procd_append_param file /etc/output-db/custom.$cfg.metadata-update.query
		procd_append_param file /etc/output-db/custom.$cfg.metadata-insert.query
		procd_append_param file /etc/output-db/custom.$cfg.data.query
		# All other options should be in UCI
		procd_close_instance
		# FIXME - need to monitor all instances!
		# monit monitor "$APP"
	fi
}

start_service() {
	config_load $APP && config_foreach add_instance instance
}

service_triggers() {
	procd_add_reload_trigger $APP
}
