#!/bin/sh /etc/rc.common
START=85
USE_PROCD=1

[ -f /lib/rme_utils.sh ] && . /lib/rme_utils.sh

remove_output() {
	local cfg="$1"
	local connection
	config_get connection "$cfg" connection
	[ -n "$connection" -a "$connection" = "senseone" ] && {
		uci delete mosquitto.$cfg
	}
}

add_output() {
	local username="$1"
	local password="$2"
	local address="$3"
	local connection
	local gateid
	gateid=$(uci -q get system.@system[0].rme_stablemac)
	local newcfg
	newcfg=$(uci add mosquitto bridge)
	uci -q batch <<-EOF
		set mosquitto.$newcfg.connection=senseone
		set mosquitto.$newcfg.address="$address"
		set mosquitto.$newcfg.cleansession=1
		set mosquitto.$newcfg.attempt_unsubscribe=false
		set mosquitto.$newcfg.notification_topic=$username/bridge/$gateid/state
		set mosquitto.$newcfg.try_private=false
		set mosquitto.$newcfg.remote_username="$username"
		set mosquitto.$newcfg.remote_password="$password"
		set mosquitto.$newcfg.cafile=/etc/ssl/certs/senseonetech-mqtt.crt
		add_list mosquitto.$newcfg.topic="/alert/new/# out 1 status/local/json $username/status"
		add_list mosquitto.$newcfg.topic="/alert/expired/# out 1 status/local/json $username/status"
		add_list mosquitto.$newcfg.topic="/cabinet/# out 1 status/local/json $username/status"
		add_list mosquitto.$newcfg.topic="/interval/15min/# out 1 status/local/json $username/status"
		commit
EOF
}

add_instance() {
	local cfg="$1"
	local enabled username password
	config_get_bool enabled "$cfg" enabled 0
	config_get username "$cfg" username
	config_get password "$cfg" password
	config_get address "$cfg" address "mqtt.senseonetech.com:8883"
	# We always remove it, and re-add it if needed.
	config_load mosquitto && config_foreach remove_output bridge
	if [ $enabled -eq 0 ]; then
		echo "Disabling SenseOne"
		rm -f /etc/cron.d/daily/republish_cabinet_model.lua
	else
		[ -z "$username" ] && { echo "username is required!"; exit 1;}
		[ -z "$password" ] && { echo "password is required!"; exit 1;}
		assert_ntp_up;
		echo "Enabling SenseOne"
		add_output $username $password $address
		[ -f /etc/cron.d/daily/republish_cabinet_model.lua ] || ln -s /usr/bin/republish_cabinet_model.lua /etc/cron.d/daily/
	fi
	uci commit
	reload_config
}

start_service() {
	procd_open_instance
	# Just something that succeeds
	procd_set_param command true
	procd_set_param file /etc/config/output-senseone
	procd_close_instance
	config_load output-senseone && config_foreach add_instance general
}

stop_service() {
	# Explicit stop just removes the bridge configs
	config_load mosquitto && config_foreach remove_output bridge
	uci commit
	reload_config
}

service_triggers() {
	procd_add_reload_trigger output-senseone
}
