#!/bin/sh /etc/rc.common
START=85
USE_PROCD=1

[ -f /lib/rme_utils.sh ] && . /lib/rme_utils.sh

remove_output() {
	local cfg="$1"
	local connection
	config_get connection "$cfg" connection
	[ "$connection" = "senseone" ] && uci -q delete mosquitto.$cfg
}

add_output() {
	local cfg="$1"
	local username="$2"
	local password="$3"
	local address="$4"
	local include_live="$5"
	local insecure="$6"
	local gateid
	gateid=$(uci -q get system.@system[0].rme_stablemac)
	local newcfg
	newcfg=$(uci add mosquitto bridge)
	uci -q batch <<-EOF
		set mosquitto.$newcfg.connection=senseone
		set mosquitto.$newcfg.address="$address"
		set mosquitto.$newcfg.cleansession=0
		set mosquitto.$newcfg.attempt_unsubscribe=false
		set mosquitto.$newcfg.notification_topic=$username/bridge/$gateid/state
		set mosquitto.$newcfg.try_private=false
		add_list mosquitto.$newcfg.topic="# out 1 ext/output-senseone/out/ $username/"
EOF
	[ -z "$password" ] || {
		echo "password was set, applying it."
		uci -q set mosquitto.$newcfg.remote_username="$username"
		uci -q set mosquitto.$newcfg.remote_password="$password"
	}
	[ "$include_live" = "true" ] && uci -q add_list mosquitto.$newcfg.topic="/device/# out 1 status/local/json $username/status"
	[ "$insecure" -eq 1 ] || uci -q set mosquitto.$newcfg.cafile=/etc/ssl/certs/senseonetech-mqtt.crt
	uci -q commit
}

add_instance() {
	local cfg="$1"
	local enabled username password address interval
	config_get_bool enabled "$cfg" enabled 0
	config_get username "$cfg" username
	config_get password "$cfg" password
	config_get address "$cfg" address "mqtt.senseonetech.com:8883"
	config_get interval "$cfg" interval "15min"
	config_get_bool insecure "$cfg" insecure 0
	# We always remove it, and re-add it if needed.
	config_load mosquitto && config_foreach remove_output bridge
	if [ $enabled -eq 0 ]; then
		echo "Disabling SenseOne"
		rm -f /etc/cron.d/daily/republish_cabinet_model.lua
		monit unmonitor output-senseone-proc
		monit unmonitor output-senseone-mqtt
	else
		[ -z "$username" ] && { echo "username is required!"; return 1;}
		[ -z "$password" ] && [ "$insecure" -eq 0 ] && { echo "password is required!"; return 1;}
		assert_ntp_up;
		echo "Enabling SenseOne"
		case "$username" in
			etactica_hq)
				add_output $cfg $username $password $address true
				;;
			marel_iceland)
				add_output $cfg $username $password $address true 1
				;;
			*)
				add_output "$cfg" "$username" "$password" "$address" false "$insecure"
				;;
		esac
		[ -f /etc/cron.d/daily/republish_cabinet_model.lua ] || ln -s /usr/bin/republish_cabinet_model.lua /etc/cron.d/daily/
		monit monitor output-senseone-proc
		monit monitor output-senseone-mqtt
	fi
	uci commit
	reload_config
	procd_open_instance
	procd_set_param command output-senseone.lua
	procd_append_param command --interval "$interval"
	procd_set_param respawn
	procd_set_param file /etc/config/output-senseone
	procd_close_instance
}

start_service() {
	config_load output-senseone && config_foreach add_instance general
}

stop_service() {
	# Explicit stop just removes the bridge configs
	config_load mosquitto && config_foreach remove_output bridge
	uci commit
	reload_config
}

service_triggers() {
	procd_add_reload_trigger output-senseone
}
